### ISSUE TITLE
Trao đổi vấn đề bài tập tảo biển

### ISSUE THREAD

**Issue by VinhDevNguyen** [hoangnhancs/CS112.L11.KHTN#1]
Chào các bạn, mình không biết liên lạc với các bạn như thế nào nên là mình quyết định sẽ trao đổi với các bạn qua Repo này, hi vọng không làm phiền các bạn.

# Fibonacci Solution
Sau khi mình giải tay như hình dưới thì mình có nhận ra công thức bài toán này giống với các bạn đã trình bày trong file [Jupiter-notebook](https://github.com/hoangnhancs/CS112.L11.KHTN/blob/master/Section2/Report.ipynb) đó là
```python
fibonacci(2*k + 1) * n
```
![image](https://user-images.githubusercontent.com/48788781/93626175-3e011a80-fa0d-11ea-9efd-8b1ef5dd70e0.png)
# Problem
Vấn đề của mình gặp phải là khi submit code lên thì hầu hết tất cả các test case của mình đều bị wrong
![image](https://user-images.githubusercontent.com/48788781/93626602-df886c00-fa0d-11ea-92a9-65cd662b4a33.png)
Không biết là nhóm các bạn đã nộp code chưa và đã được full điểm chưa, nếu full điểm rồi hy vọng nhóm bạn có thể cho mình một chút gợi ý để cái thiện bài làm của mình. Còn nếu chưa thì có thể trao đổi với nhau thêm thông qua issue này bằng cách comment ở dưới.

Cảm ơn nhóm bạn đã đọc.

**Comment by sonlhcsuit** [comment]
Hi Vinh, về vấn đề này thì bạn kiểm tra lại đề bài nhé. Dòng cuối đề có yêu cầu xuất dưới dạng mô dun 1000000007. Nghĩa là sau khi tính ra theo công thức thì nhớ mod với số kia để ra kết quả.

**Comment by VinhDevNguyen** [comment]
@sonlhcsuit Hi bạn, mình có sử dụng [công thức để tính Fibonacci](http://www.maths.surrey.ac.uk/hosted-sites/R.Knott/Fibonacci/fibFormula.html#section1.1) và có xuất ra dưới dạng mô đun 10^9 + 7 rồi. Vấn đề là do công thức đó khi `k` quá lớn sẽ bị sai số nên kết quả mình ra sai.
# Another Solution
Mình có tham khảo [Method 5](https://www.geeksforgeeks.org/program-for-nth-fibonacci-number/) trên trang geeksforgeeks.org và thử submit code nhưng vẫn có một test case chạy lố thời gian quy định. Không biết nhóm các bạn làm như thế nào?

**Comment by sonlhcsuit** [comment]
À rồi về cơ bản thì bạn phải liên tục module từng số fib khi lặp. ví dị chẳng hạn đi fib(800) = fib(799)+fib(798) thì chúng ta sẽ ko quan tâm tới cái số cụ thể mà ta phải quan tâm tới : f(800)%M (M=10^9+7) = ( f(799)%M + f(798)%M )%M >nếu cải tiến thế này thì nó sẽ ko còn là fib seq nữa nhưng sẽ giải quyết được. Nếu vòng lặp vẫn còn bị thi sử dụng cách này xem thử nhé ;) 
[click here](https://codeforces.com/blog/entry/14516)
