### ISSUE TITLE
Góp ý link Google Colab

### ISSUE THREAD

**Issue by VinhDevNguyen** [hoangnhancs/CS112.L11.KHTN#2]
Mình thấy nhóm bạn viết [báo cáo](https://github.com/hoangnhancs/CS112.L11.KHTN/blob/master/Section3/Report.ipynb) dùng code dưới ở bên dưới để chèn biểu tượng Colab với link nhưng khi bấm vào thì nó không chuyển hướng sang link Colab mà phải bắt buộc bấm tổ hợp phím `ctrl + click` thì mới chuyển hướng
```
[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/hoangnhancs/CS112.L11.KHTN/blob/master/Section3/Report.ipynb)
```
Bạn thử dùng code dưới này của mình xem có cải thiện được tình trạng đó không?
```
<a href="https://colab.research.google.com/github/hoangnhancs/CS112.L11.KHTN/blob/master/Section3/Report.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>
```

**Comment by sonlhcsuit** [comment]
Cảm ơn bạn đã đóng góp ý kiến, mình viết thì nó hoạt động với máy mình nên viết dòng đó để phòng hờ thôi. Lúc mình click vào thì vẫn mở sang tab mới
